-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.5.16 - MySQL Community Server (GPL)
-- Server OS:                    Win32
-- HeidiSQL version:             7.0.0.4053
-- Date/time:                    2013-11-27 00:16:06
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET FOREIGN_KEY_CHECKS=0 */;

-- Dumping database structure for scripingairasia
DROP DATABASE IF EXISTS `scripingairasia`;
CREATE DATABASE IF NOT EXISTS `scripingairasia` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `scripingairasia`;


-- Dumping structure for table scripingairasia.station_list
DROP TABLE IF EXISTS `station_list`;
CREATE TABLE IF NOT EXISTS `station_list` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CODE` varchar(255) DEFAULT NULL,
  `COUNTRY_CODE` varchar(255) DEFAULT NULL,
  `MAC_CODE` varchar(255) DEFAULT NULL,
  `NAME` text,
  `PROVINCE_STATE_CODE` varchar(255) DEFAULT NULL,
  `SHORT_NAME` varchar(255) DEFAULT NULL,
  `STATION_CATEGORIES` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=152 DEFAULT CHARSET=latin1;

-- Dumping data for table scripingairasia.station_list: ~151 rows (approximately)
DELETE FROM `station_list`;
/*!40000 ALTER TABLE `station_list` DISABLE KEYS */;
INSERT INTO `station_list` (`ID`, `CODE`, `COUNTRY_CODE`, `MAC_CODE`, `NAME`, `PROVINCE_STATE_CODE`, `SHORT_NAME`, `STATION_CATEGORIES`) VALUES
	(1, 'ADL', 'AU', '', 'Adelaide', 'SA', 'Adelaide Airport', ''),
	(2, 'ROR', 'PW', '', 'Airai Airport', 'OTH', 'Airai Airport', 'C'),
	(3, 'AOR', 'MY', '', 'Alor Setar', 'KED', 'Alor Setar', ''),
	(4, 'BCD', 'PH', '', 'Bacolod', 'NEC', 'Bacolod', ''),
	(5, 'BGW', 'IQ', '', 'Baghdad International Airport', 'BG', 'Baghdad International Airport', 'C'),
	(6, 'BTJ', 'ID', '', 'Banda Aceh', 'AC', 'Banda Aceh', ''),
	(7, 'BDO', 'ID', '', 'Bandung', 'JB', 'Bandung', ''),
	(8, 'BLR', 'IN', '', 'Bangalor', 'KA', 'Bangalore', ''),
	(9, 'BKK', 'TH', 'BAK', 'Bangkok', 'AS', 'Bangkok', 'C'),
	(10, 'DMK', 'TH', '', 'Bangkok – Don Mueang ', 'AS', 'Bangkok', ''),
	(11, 'PEK', 'CN', '', 'Beijing', 'AC', 'Beijing', ''),
	(12, 'BEY', 'LB', '', 'Beirut International Airport', 'BA', 'Beirut International Airport', 'C'),
	(13, 'BTU', 'MY', '', 'Bintulu', 'SWR', 'Bintulu', ''),
	(14, 'TLS', 'FR', '', 'Blagnac Airport', 'OTH', 'Blagnac Airport', 'C'),
	(15, 'BWN', 'BN', '', 'Brunei', '', 'Brunei', ''),
	(16, 'BFV', 'TH', '', 'Buri Ram (Charter)', 'AC', 'Buri Ram (Charter)', 'C'),
	(17, 'PUS', 'KR', '', 'Busan', 'OTH', 'Busan', ''),
	(18, 'CGY', 'PH', '', 'Cagayan de Oro', 'CAG', 'Cagayan de Oro', ''),
	(19, 'CEB', 'PH', '', 'Cebu', 'CEB', 'Cebu', ''),
	(20, 'SIN', 'SG', '', 'Singapura', 'SGN', 'Changi Airport - Terminal 1', ''),
	(21, 'CSX', 'CN', '', 'Changsha (Charter)', 'AO', 'Changsha (charter)', 'C'),
	(22, 'CTU', 'CN', '', 'Chengdu', 'AZ', 'Chengdu', ''),
	(23, 'MAA', 'IN', '', 'Chennai', '', 'Chennai', ''),
	(24, 'CNX', 'TH', '', 'Chiang Mai', '', 'Chiang Mai', ''),
	(25, 'CEI', 'TH', '', 'Chiang Rai', '', 'Chiang Rai', ''),
	(26, 'CKG', 'CN', '', 'Chongqing', 'AD', 'Chongqing', ''),
	(27, 'CHC', 'NZ', '', 'Christchurch', 'CAN', 'Christchurch', 'C'),
	(28, 'CRK', 'PH', '', 'Clark', 'PAM', 'Clark (2hrs drive to Manila)', ''),
	(29, 'CMB', 'LK', '', 'Kolombo', 'E', 'Colombo ', ''),
	(30, 'DAD', 'VN', '', 'Da Nang', 'AQ', 'Da Nang', ''),
	(31, 'DLC', 'CN', '', 'Dalian Airport', 'AS', 'Dalian Airport', 'C'),
	(32, 'DRW', 'AU', '', 'Darwin', 'NT', 'Darwin Airport', ''),
	(33, 'DVO', 'PH', '', 'Davao', 'DAS', 'Davao', ''),
	(34, 'DEL', 'IN', '', 'New Delhi', 'DL', 'New Delhi', 'C'),
	(35, 'DPS', 'ID', '', 'Bali', 'BA', 'Bali', ''),
	(36, 'L1A', 'TH', '', 'Donsak Pier', 'IL', 'Donsak Pier', 'C'),
	(37, 'DXB', 'AE', '', 'Dubai Airport', 'DU', 'Dubai Airport', 'C'),
	(38, 'GAY', 'IN', '', 'Gaya Airport', 'BR', 'Gaya Airport (Charter)', 'C'),
	(39, 'OOL', 'AU', '', 'Gold Coast', 'QLD', 'Gold Coast (Brisbane)', ''),
	(40, 'CAN', 'CN', '', 'Guangzhou', '', 'Guangzhou', ''),
	(41, 'KWL', 'CN', '', 'Guilin', 'AH', 'Guilin', ''),
	(42, 'KWE', 'CN', '', 'Guiyang (Charter)', 'AI', 'Guiyang (Charter)', 'C'),
	(43, 'HND', 'JP', '', 'Tokyo - Haneda', 'CC', 'Tokyo', ''),
	(44, 'HGH', 'CN', '', 'Hangzhou', 'BG', 'Hangzhou (Shanghai)', ''),
	(45, 'HAN', 'VN', '', 'Hanoi', 'AZ', 'Hanoi', ''),
	(46, 'HRB', 'CN', '', 'Harbin Airport', 'AL', 'Harbin Airport', 'C'),
	(47, 'HDY', 'TH', '', 'Hat Yai', '', 'Hat Yai', ''),
	(48, 'HFE', 'CN', '', 'Hefei (Charter)', 'AA', 'Hefei (Charter)', 'C'),
	(49, 'SGN', 'VN', '', 'Ho Chi Minh City', 'BE', 'Ho Chi Minh City', ''),
	(50, 'HKG', 'HK', '', 'Hong Kong', 'OTH', 'Hong Kong', ''),
	(51, 'SHA', 'CN', '', '??????', 'OTH', 'Shanghai', 'C'),
	(52, 'ILO', 'PH', '', 'Iloilo', 'ILI', 'Iloilo', ''),
	(53, 'ICN', 'KR', '', 'Seoul', 'K', 'Seoul', ''),
	(54, 'CGK', 'ID', '', 'Jakarta', 'BT', 'Jakarta', ''),
	(55, 'JED', 'SA', '', 'Jeddah', 'K', 'Jeddah', ''),
	(56, 'JJN', 'CN', '', 'Jinjiang', 'AE', 'Jinjiang Airport', 'C'),
	(57, 'JHB', 'MY', '', 'Johor Bahru', 'JHB', 'Johor Bahru', ''),
	(58, 'KLO', 'PH', '', 'Kalibo - Boracay', 'AKL', 'Kalibo (Boracay)', ''),
	(59, 'KTM', 'NP', '', 'Kathmandu', 'BA', 'Kathmandu', ''),
	(60, 'KKC', 'TH', '', 'Khon Kaen', 'AQ', 'Khon Kaen Airport', ''),
	(61, 'COK', 'IN', '', 'Kochi', 'KL', 'Kochi', ''),
	(62, 'CCU', 'IN', '', 'Kolkata', 'WB', 'Kolkata', ''),
	(63, 'KBR', 'MY', '', 'Kota Bharu', 'KEL', 'Kota Bharu', ''),
	(64, 'BKI', 'MY', '', 'Kota Kinabalu', 'SAB', 'Kota Kinabalu', ''),
	(65, 'KBV', 'TH', '', 'Krabi', '', 'Krabi', ''),
	(66, 'KUL', 'MY', '', 'Kuala Lumpur', 'KUL', 'Kuala Lumpur LCCT', ''),
	(67, 'TGG', 'MY', '', 'Kuala Terengganu', 'TGG', 'Kuala Terengganu', ''),
	(68, 'KUA', 'MY', '', '??????', 'PHA', 'Kuantan Airport', 'C'),
	(69, 'KCH', 'MY', '', 'Kuching', 'SWR', 'Kuching', ''),
	(70, 'KMG', 'CN', '', 'Kunming', 'BF', 'Kunming', ''),
	(71, 'LBU', 'MY', '', 'Labuan', '', 'Labuan', ''),
	(72, 'LGK', 'MY', '', 'Langkawi', 'KED', 'Langkawi', ''),
	(73, '1AD', 'TH', '', 'Lanta (Dermaga Saladan)', 'IL', 'Lanta (Saladan Pier)', ''),
	(74, '1AE', 'TH', '', 'Lipe (Pantai Sunrise) ', 'IL', 'Lipe (Sunrise Beach)', ''),
	(75, 'LOP', 'ID', '', 'Lombok', 'NB', 'Lombok', ''),
	(76, 'LGW', 'GB', '', 'London', 'EN', 'London', 'C'),
	(77, 'MFM', 'MO', '', 'Macau', 'OTH', 'Macau', ''),
	(78, 'MLE', 'MV', '', 'Male', 'N', 'Male International Airport', ''),
	(79, 'MDC', 'ID', '', 'Manado', 'SA', 'Manado', ''),
	(80, 'MDL', 'MM', '', 'Mandalay', 'H', 'Mandalay', ''),
	(81, 'MNL', 'PH', '', 'Manila', 'MNL', 'Manila', ''),
	(82, 'MES', 'ID', '', 'Medan', 'SU', 'Medan', 'C'),
	(83, 'KNO', 'ID', '', 'Medan - Kualanamu', 'SU', 'Medan Kualanamu', ''),
	(84, 'MEL', 'AU', '', 'Melbourne', 'VIC', 'Melbourne', ''),
	(85, 'MYY', 'MY', '', 'Miri', 'SWR', 'Miri', ''),
	(86, 'MWX', 'KR', '', 'Muan (Charter)', 'N', 'Muan (Charter)', 'C'),
	(87, 'BOM', 'IN', '', 'Mumbai', 'MH', 'Mumbai', 'C'),
	(88, 'KOP', 'TH', '', 'Nakhon Phanom', 'BC', 'Nakhon Phanom', ''),
	(89, 'NST', 'TH', '', 'Nakhon Si Thammarat', '', 'Nakhon Si Thammarat', ''),
	(90, 'NKG', 'CN', '', 'Guiyang (Charter)', 'AP', 'Nanjing (Charter)', 'C'),
	(91, 'NNG', 'CN', '', 'Nanning', 'AH', 'Nanning', ''),
	(92, 'NAW', 'TH', '', 'Narathiwat', '', 'Narathiwat', ''),
	(93, 'NYT', 'MM', '', 'Nay Pyi Taw', 'B', 'Nay Pyi Taw', ''),
	(94, '1AF', 'TH', '', 'Ngai (KohNgai Villa)', 'IL', 'Ngai (Koh Ngai Villa)', ''),
	(95, 'NGB', 'CN', '', 'Ningbo Airport', 'BG', 'Ningbo Airport', 'C'),
	(96, 'L1F', 'TH', '', 'Nopparattara Pier', 'IL', 'Nopparattara Pier', 'C'),
	(97, 'L1C', 'TH', '', 'Nopparatthara Pier', 'IL', 'Nopparatthara Pier', 'C'),
	(98, 'KIX', 'JP', '', 'Osaka - Kansai', 'CI', 'Osaka', ''),
	(99, 'PDG', 'ID', '', 'Padang', 'SB', 'Padang', ''),
	(100, 'L1D', 'TH', '', 'Pakbara Pier', 'IL', 'Pakbara Pier', 'C'),
	(101, 'L1E', 'TH', '', 'Pakmeng Pier', 'IL', 'Pakmeng Pier', 'C'),
	(102, 'PLM', 'ID', '', 'Palembang', 'SS', 'Palembang', ''),
	(103, 'ORY', 'FR', '', 'Paris', 'DC', 'Paris', 'C'),
	(104, 'PKU', 'ID', '', 'Pekanbaru', 'RI', 'Pekanbaru', ''),
	(105, 'PEN', 'MY', '', 'Penang', 'PEN', 'Penang', ''),
	(106, 'PER', 'AU', '', 'Perth', 'WA', 'Perth', ''),
	(107, '1AB', 'TH', '', 'Phangan (Dermaga Thong Sala)', 'IL', 'Phangan (Thong Sala Pier)', ''),
	(108, '1AC', 'TH', '', 'Phi Phi (Dermaga Phi Phi) ', 'IL', 'Phi Phi (Phi Phi Pier)', ''),
	(109, 'PHS', 'TH', '', 'Phitsanulok', 'BU', 'Phitsanulok ', ''),
	(110, 'PNH', 'KH', '', 'Phnom Penh', '', 'Phnom Penh', ''),
	(111, 'HKT', 'TH', '', 'Phuket', '', 'Phuket', ''),
	(112, 'PPS', 'PH', '', 'Puerto Princesa - Palawan', 'PLW', 'Puerto Princesa (Palawan)', ''),
	(113, 'TAO', 'CN', '', 'Qingdao (Charter)', 'AX', 'Qingdao (Charter)', 'C'),
	(114, 'L1B', 'TH', '', 'Rassada Pier', 'IL', 'Rassada Pier', 'C'),
	(115, '1AA', 'TH', '', 'Samui (Pelabuhan Lipa Noi)', 'IL', 'Samui (Lipa Noi Pier)', ''),
	(116, 'SDK', 'MY', '', 'Sandakan', '', 'Sandakan', ''),
	(117, 'SRG', 'ID', '', 'Semarang', 'JT', 'Semarang', ''),
	(118, 'BPN', 'ID', '', 'Balikpapan', 'KI', 'Balikpapan', ''),
	(119, 'PVG', 'CN', '', 'Shanghai', 'AA', 'Shanghai', ''),
	(120, 'SHJ', 'AE', '', 'Sharjah Airport', 'SH', 'Sharjah Airport', 'C'),
	(121, 'SZX', 'CN', '', 'Shenzhen', '', 'Shenzhen', ''),
	(122, 'SBW', 'MY', '', 'Sibu', '', 'Sibu', ''),
	(123, 'REP', 'KH', '', 'Siem Reap', '', 'Siem Reap', ''),
	(124, 'SOC', 'ID', '', 'Solo', 'JT', 'Solo', ''),
	(125, 'SZB', 'MY', '', 'Sultan Abdul Aziz Shah Airport', 'KUL', 'Sultan Abdul Aziz Shah Airport', 'C'),
	(126, 'SUB', 'ID', '', 'Surabaya', 'JI', 'Surabaya', ''),
	(127, 'URT', 'TH', '', 'Surat Thani', '', 'Surat Thani', ''),
	(128, 'SYD', 'AU', '', 'Sydney', 'NS', 'Sydney', ''),
	(129, 'TAC', 'PH', '', 'Tacloban', 'LEY', 'Tacloban', ''),
	(130, 'TAG', 'PH', '', 'Tagbilaran', 'BOH', 'Tagbilaran ', ''),
	(131, 'TPE', 'TW', '', 'Taipei', 'TPE', 'Taipei', ''),
	(132, 'TWU', 'MY', '', 'Tawau', '', 'Tawau', ''),
	(133, 'IKA', 'IR', '', 'Tehran', 'BF', 'Tehran', 'C'),
	(134, 'TRZ', 'IN', '', 'Tiruchirappalli', 'TN', 'Tiruchirappalli', ''),
	(135, 'TST', 'TH', '', 'Trang', 'CT', 'Trang', ''),
	(136, 'UBP', 'TH', '', 'Ubon Ratchathani', '', 'Ubon Ratchathani', ''),
	(137, 'UTH', 'TH', '', 'Udon Thani', '', 'Udon Thani', ''),
	(138, 'UPG', 'ID', '', 'Makassar', 'SN', 'Makassar', ''),
	(139, 'VTE', 'LA', '', 'Vientiane', 'VT', 'Vientiane', ''),
	(140, 'WNZ', 'CN', '', 'Wenzhou (Charter)', 'BG', 'Wenzhou (Charter) ', 'C'),
	(141, 'WUH', 'CN', '', 'Wuhan', 'AN', 'Wuhan', ''),
	(142, 'XIY', 'CN', '', 'Xi\'an', 'AW', 'Xi\'an', ''),
	(143, 'RGN', 'MM', '', 'Yangoon', 'N', 'Yangon', ''),
	(144, '1AG', 'TH', '', 'Yao Noi (Dermaga Manoh)', 'IL', 'Yao Noi (Manoh Pier)', ''),
	(145, 'JOG', 'ID', '', 'Yogyakarta', 'YO', 'Yogyakarta', ''),
	(146, 'CGO', 'CN', '', 'Zhengzhou Airport', 'AM', 'Zhengzhou Airport', 'C'),
	(147, 'XCH', 'CX', '', 'Christmas Island Airport', 'OTH', 'Christmas Island Airport', 'C'),
	(148, 'NGO', 'JP', '', 'Nagoya - Chubu', 'AA', 'Chubu Centrair International Air', ''),
	(149, '3AA', 'TH', '', 'Pai', 'IL', 'Pai', 'C'),
	(150, '3AB', 'TH', '', 'Sukhothai', 'IL', 'Sukhothai', 'C'),
	(151, 'L1G', 'TH', '', 'Hua Hin Pier', 'IL', 'Hua Hin Pier', 'C');
/*!40000 ALTER TABLE `station_list` ENABLE KEYS */;
/*!40014 SET FOREIGN_KEY_CHECKS=1 */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
